[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "memory"
description = "The virtual memory subsystem."
version = "0.1.0"

[dependencies]
spin = "0.9.0"
bitflags = "1.1.0"
bit_field = "0.7.0"
zerocopy = "0.5.0"
log = "0.4.8"
lazy_static = { version = "1.4.0", features = [ "spin_no_std" ] }
irq_safety = { git = "https://github.com/theseus-os/irq_safety" }

atomic_linked_list = { path = "../../../libs/atomic_linked_list" }

frame_allocator = { path = "../../../kernel/frame_allocator" }
page_allocator = { path = "../../../kernel/page_allocator" }
memory_structs = { path = "../../../kernel/memory_structs" }
kernel_config = { path = "../../../kernel/kernel_config" }
page_table_entry = { path = "../page_table_entry" }
pte_flags = { path = "../../../kernel/pte_flags" }
no_drop = { path = "../../../kernel/no_drop" }

memory_aarch64 = { path = "../memory_aarch64" }
