name: Release

on:
  push: { tags: ['v*'] }

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Authenticate crates.io
      env:
        CRATES_IO_TOKEN: ${{ secrets.crates_io_token }}
      run: cargo login $CRATES_IO_TOKEN

    - name: Publish crate
      run: cargo publish