[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "page_table_entry"
description = "Defines the structure of page table entries on x86_64"
version = "0.1.0"
edition = "2018"

[dependencies]
bit_field = "0.7.0"
zerocopy = "0.5.0"

kernel_config = { path = "../kernel_config" }
memory_structs = { path = "../memory_structs" }
frame_allocator = { path = "../frame_allocator" }
pte_flags = { path = "../../../kernel/pte_flags" }

[lib]
crate-type = ["rlib"]
