[package]
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
name = "cpu"
description = "An abstraction over the discovery of processor cores"
version = "0.1.0"
edition = "2021"

[target.'cfg(target_arch = "x86_64")'.dependencies]
apic = { path = "../apic" }

[lib]
crate-type = ["rlib"]
