[package]
name = "fault_log"
version = "0.1.0"
description = "Logs all exceptions occuring in Theseus"
authors = ["Namitha Liyanage <namithaliyanage@gmail.com>"]

[dependencies]
irq_safety = { git = "https://github.com/theseus-os/irq_safety" }
memory = { path = "../memory" }
app_io = { path = "../app_io" }
task = { path = "../task" }
cpu = { path = "../cpu" }
log = { default-features = false, version = "0.4.8" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
vga_buffer = { path = "../vga_buffer" }
