[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "page_allocator"
description = "The allocator for virtual memory frames."
version = "0.1.0"

[lib]
path = "lib.rs"

[dependencies]
spin = "0.9.0"
static_assertions = "1.1.0"
memory_structs = { path = "../memory_structs" }
static_array_collections = { path = "../static_array_collections" }
kernel_config = { path = "../kernel_config" }
log = "0.4.8"
