[package]
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
description = "Allows configuring the Generic Interrupt Controller"
version = "0.1.0"
edition = "2021"
name = "gic"

[dependencies]
static_assertions = "1.1.0"
bitflags = "1.1.0"
zerocopy = "0.5.0"

irq_safety = { git = "https://github.com/theseus-os/irq_safety" }

memory = { path = "../memory" }
