[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>", "Nathan Royer <nathan.royer.pro@gmail.com>"]
name = "interrupts"
description = "Interrupt configuration and handlers for Theseus"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
spin = "0.9.4"

[target.'cfg(target_arch = "aarch64")'.dependencies]
cortex-a = "7.5.0"
tock-registers = "0.7.0"
gic = { path = "../gic" }
memory = { path = "../memory" }
irq_safety = { git = "https://github.com/theseus-os/irq_safety" }

[lib]
crate-type = ["rlib"]
