[package]
name = "nano_core"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nano_core"
path = "main.rs"

[dependencies]
log = "0.4.17"
logger = { path = "../logger" }

[dependencies.uefi]
git = "https://github.com/theseus-os/uefi-rs/"
branch = "until-upstream-pr-merged"
default-features = false
features = [ "alloc", "exts" ]

[dependencies.uefi-services]
git = "https://github.com/theseus-os/uefi-rs/"
branch = "until-upstream-pr-merged"
default-features = false
features = [ "panic_handler" ]
