[package]
name = "pte_flags"
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
description = "The flags for page table entries/slots."
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"

[lib]
path = "lib.rs"
crate-type = ["rlib"]
