[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "catch_unwind"
description = "Support for catching unwinding after a panic, like `std::panic::catch_unwind`"
version = "0.1.0"

[dependencies]
log = "0.4.8"

task = { path = "../task" }

[target.'cfg(target_arch = "x86_64")'.dependencies]
unwind = { path = "../unwind" }

[lib]
crate-type = ["rlib"]
