[package]
authors = ["Nathan Royer <nathan.royer.pro@gmail.com>"]
name = "context_switch_regular"
description = "Context switching routines and structs for regular (non-SSE) register sets, aarch64 version"
version = "0.1.0"

[dependencies]
zerocopy = "0.5.0"

[lib]
crate-type = ["rlib"]
