[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "logger_x86_64"
version = "0.1.0"

[dependencies]
log = "0.4.8"
irq_safety = { git = "https://github.com/theseus-os/irq_safety" }
spin = "0.9.4"
serial_port_basic = { path = "../serial_port_basic" }

[lib]
crate-type = ["rlib"]
