cargo-path = "cargo"
arch = "x86_64"

[prefixes]
kernel = "k#"
applications = "a#"
executables = "e#"

[build-cells]
cargo-target = "x86_64-theseus"
build-mode = "release"

[link-nano-core]
linker = "ld"

[serialize-nano-core-syms]
readelf = "readelf"
