[package]
name = "logger_aarch64"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
log = "0.4.17"

memory = { path = "../memory" }

irq_safety = { git = "https://github.com/theseus-os/irq_safety" }
pl011_qemu = { git = "https://github.com/theseus-os/pl011/", branch = "aarch64-qemu-virt-test" }
