[package]
authors = ["Kevin Boos <kevinaboos@gmail.com>"]
name = "memory_structs"
description = "Common types used in the memory management subsystem"
version = "0.1.0"

[dependencies]
bit_field = "0.7.0"
zerocopy = "0.5.0"
derive_more = "0.99.0"
paste = "1.0.5"

[lib]
path = "lib.rs"
